version: '3'

services:
  mariadb:
    image: mariadb:10.6
    restart: always
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
    environment:
      MYSQL_ROOT_PASSWORD: "your_strong_password"
    ports:
      - "3306:3306" # Opens the port to your internal LAN
    volumes:
      - mariadb-data:/var/lib/mysql

  # ERPNext also requires Redis. We can host it on the same DB node.
  redis-cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"

  redis-queue:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6380:6379"

volumes:
  mariadb-data:
